<?php
/**
 * Child theme bootstrap for sg-texbuilt.
 * Auto-generated by ccc-client-importer; extended for custom blocks + CSS.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Frontend enqueues: Google fonts + child stylesheet loaded AFTER parent
 * blocks.css so child-theme rules win on equal specificity.
 */
add_action( 'wp_enqueue_scripts', function () {
	wp_enqueue_style(
		'sg-texbuilt-google-fonts',
		'https://fonts.googleapis.com/css2?family=Barlow%20Condensed:wght@500;600;700&family=Source%20Sans%203:wght@400;500;600;700&display=swap',
		array(),
		null
	);
	wp_enqueue_style(
		'sg-texbuilt-style',
		get_stylesheet_uri(),
		array( 'ccc-blocks' ),
		file_exists( get_stylesheet_directory() . '/style.css' )
			? (string) filemtime( get_stylesheet_directory() . '/style.css' )
			: '1.0.0'
	);
}, 20 );

/**
 * Pull the child stylesheet into the block editor iframe too, so preview-mode
 * blocks render with the same CSS they'll ship with.
 */
add_action( 'after_setup_theme', function () {
	add_editor_style( 'style.css' );
} );

/**
 * Auto-register ACF blocks from sg-texbuilt/blocks/{slug}/. Mirrors the
 * parent's block loader (inc/blocks.php) but scoped to the child directory.
 */
add_action( 'init', function () {
	$blocks_dir = get_stylesheet_directory() . '/blocks';
	if ( ! is_dir( $blocks_dir ) ) return;
	foreach ( glob( $blocks_dir . '/*', GLOB_ONLYDIR ) as $block_path ) {
		if ( file_exists( $block_path . '/block.json' ) ) {
			register_block_type_from_metadata( $block_path );
		}
	}
}, 5 );

add_action( 'acf/include_fields', function () {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) return;
	foreach ( glob( get_stylesheet_directory() . '/blocks/*/fields.php' ) as $fields_file ) {
		require_once $fields_file;
	}
}, 5 );

/**
 * Register an "Accent Script" block style on core heading, paragraph, and
 * quote blocks. The style applies the Mitha Script font family (registered
 * via theme.json) so editors can flip any of those blocks to the accent
 * treatment with one click in the block style picker.
 *
 * CSS for the `.is-style-accent-font` class lives in style.css.
 */
add_action( 'init', function () {
	$label   = __( 'Accent Script', 'sg-texbuilt' );
	$targets = array( 'core/heading', 'core/paragraph', 'core/quote' );
	foreach ( $targets as $block_name ) {
		register_block_style( $block_name, array(
			'name'  => 'accent-font',
			'label' => $label,
		) );
	}
} );

/**
 * Register a "Large Script" block style on core paragraph. Applies the
 * Mitha Script accent font + a fluid clamp font-size (3.037rem -> 6rem
 * across the viewport) so the cursive renders at a usable display scale
 * without per-block font-size overrides.
 *
 * CSS for the `.is-style-large-script` class lives in style.css.
 */
add_action( 'init', function () {
	register_block_style( 'core/paragraph', array(
		'name'  => 'large-script',
		'label' => __( 'Large Script', 'sg-texbuilt' ),
	) );
} );

/**
 * Gravity Forms: render submit buttons with the same classes a WP core
 * Button block uses, so they pick up theme.json's `elements.button`
 * styling AND the parent theme's palette pair-helpers automatically.
 *
 * Filter signature: `gform_submit_button( $button_html, $form )` — we
 * replace the entire <input>/<button> markup. Keeping the `gform_button`
 * class so any GF-specific JS hooks (validation submit-handlers, etc.)
 * still find the element. Adding `has-cta-background-color has-background`
 * applies the CTA palette pair (bg + opposite text), and
 * `wp-block-button__link wp-element-button` pulls in WP's button typography,
 * radius, padding, and hover transitions from theme.json.
 */
add_filter( 'gform_submit_button', function ( $button, $form ) {
	$form_id = absint( $form['id'] ?? 0 );
	$text    = $form['button']['text'] ?? __( 'Submit', 'sg-texbuilt' );
	$classes = 'gform_button wp-block-button__link wp-element-button has-cta-background-color has-background';
	return sprintf(
		'<button type="submit" id="gform_submit_button_%1$d" class="%2$s">%3$s</button>',
		$form_id,
		esc_attr( $classes ),
		esc_html( $text )
	);
}, 10, 2 );
